#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd mesh

# Blockmesh
runApplication blockMesh -dict system/blockMeshDict

cd ..

# ----------------------------------------------------------------- end-of-file
